name: Assignment1 Backend CI

on:
  push:
    branches:
      - main # Trigger CI on pushes to the main branch

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22] # Test on multiple Node.js versions

    environment: MONGO_URI

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Print Env Secret

        env:
          MONGO_URI: MONGO_URI=mongodb+srv://qut636_1:1234@cluster0.nspoova.mongodb.net/petclinic?retryWrites=true&w=majority&appName=Cluster0
          JWT_SECRET: JWT_SECRET=2J8zqkP7VN6bxzg+Wy7DQZsd3Yx8mF3Bl0kch6HYtFs=
          PORT: PORT=5002
        run: |
          echo "Secret 1 is: $MONGO_URI"
          echo "Secret 2 is: $JWT_SECRET"
          echo "Secret 3 is: $PORT"

      - run: pm2 stop all

      # Install dependencies for backend
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          npm install --global yarn
          yarn --version
          yarn install

      # Install dependencies for frontend
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
          df -h
          sudo rm -rf ./build
          yarn install
          yarn run build

      # Run backend tests
      - name: Run Backend Tests
        env:
          MONGO_URI: MONGO_URI=mongodb+srv://qut636_1:1234@cluster0.nspoova.mongodb.net/petclinic?retryWrites=true&w=majority&appName=Cluster0
          JWT_SECRET: JWT_SECRET=2J8zqkP7VN6bxzg+Wy7DQZsd3Yx8mF3Bl0kch6HYtFs=
          PORT: PORT=5002
        working-directory: ./backend
        run: npm test

      - run: npm ci
      - run: |
          cd ./backend
          touch .env
          echo "${{ secrets.PROD }}" > .env

      - run: pm2 start all

      - run: pm2 restart all
